# Generated by Django 3.1.7 on 2021-03-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210321_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_description',
            field=models.TextField(blank=True, default='Your Todo Details'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task_title',
            field=models.CharField(default='Your TODO Here..', max_length=255),
        ),
    ]
