# Generated by Django 3.1.7 on 2021-03-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210321_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
